/* TYPE MA APRE KOI PN EK J NAME VALI VASTU USE NAI THY ATLE ANE AMA APRE STORE KRI DAI A CONST API NE EK VARIABLE MA ATLE HVE A NAME NO TYPE HVE BIJI VAR USE NAI KARI SAKAY */
/* KOI PN TYPE DEFINE KARVO HOI TO AHI KARVANO */

export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";